### ISSUE TITLE
Parameter must be an array or an object that implements Countable - PHP 7.2

### ISSUE THREAD

**Issue by chrisjimallen** [mindkomm/timber-integration-woocommerce#10]
I'm getting the following error when using a `single-product.twig`.

```
Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-includes/post-template.php on line 285
```

The $pages array is null at the point where `the_content()` is called in  `wp-content/plugins/woocommerce/templates/single-product/tabs/description.php`

It appears this is a common error when `the_content()` is called _outside_ of the loop. but as far as I can see it should be in it. At least it is when using a non-timber theme such as TwentySixteen.

I'm using the timber start theme.

<img width="1016" alt="screenshot 2018-11-29 at 23 04 21" src="https://user-images.githubusercontent.com/1681063/49258002-cf179380-f42b-11e8-8f55-1c0e21a41aab.png">

**Comment by gchtr** [comment]
Sorry for the late answer!

You are right, this happens when `the_content()` or `get_the_content()` is called outside of the loop. This is probably an issue with WordPress itself, see https://core.trac.wordpress.org/ticket/42814. 

I’d advise you to use a custom Twig template for the description tab. Add a **views/woocommerce/single-product/tabs/description.twig** template to your theme with the following contents:

```twig
{% set heading = __('Description', 'woocommerce')
    |apply_filters('woocommerce_product_description_heading')
    |e('esc_html')
%}

{% if heading %}
    <h2>{{ heading }}</h2>
{% endif %}

{{ post.content }}
```

When we use `$post->content()`, there shouldn’t be a problem.
