### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by Frulko** [mindkomm/timber-integration-woocommerce#13]
Ok, it's not about a problem, just to say thank you !

I use your woocommerce integration and it's very cool to use both timber and woocommerce, it works like a charm.

The project is still maintained ? What about the "next" branch release ?
I would participate on this project after the end of my current woocommerce/timber project. 

Have a nice day !

**Comment by gchtr** [comment]
Hey @Frulko! Thanks, it’s great to hear that it’s working well for you!

It’s still maintained yes, though I’m not actively working on new features now. There will be some bigger updates as soon as Timber 2.0 is coming, which should simplify this integration (see #6).

I have to admit that I forgot about the `next` branch, probably because nobody raised an issue for a long time 😅 and I didn’t work on new WooCommerce projects.

You’re always welcome to participate! You could either create a new issue to discuss what you had in mind or create a pull request directly.

**Comment by epiphaneSpecter** [comment]
I am not yet doing the integration of your package. But just to read the features. I'm in love. I will also contribute if from here timber it does not clog the cu to offer us a good integration. good job.
