### ISSUE TITLE
How to get featured posts to show up

### ISSUE THREAD

**Issue by azeem-khan** [mindkomm/timber-integration-woocommerce#25]
How would I be able to show featured posts within a loop. I assumed it would be the same as get related products but instead using wc_get_featured_product_ids() but that does not seem to work. 

Would you be able to point me in the right direction on how to implement this?

Many thanks

**Comment by gchtr** [comment]
Hey @azeem-khan 

That’s a really good question and something that’s not obviouse at all. I’ll want to document this better, because getting and displaying a bunch of products is a use case that will come up quite often.

But before I write the documentation for this, I’d be glad if you could try out the following solution.

First, you will need the newest [release candidate](https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.1-rc.1), because I added some fixes there that make this work without any workarounds:

```bash
composer require mindkomm/timber-integration-woocommerce:0.6.1-rc.1
```

First, you would have to prepare the products. You can use `wc_get_featured_product_ids()` for this, which you then have to convert to Timber posts. Additionally, these posts should be wrapped in a `PostCollection`.

```php
$posts = new PostCollection( Timber::get_posts( wc_get_featured_product_ids() ) );
```

You then need to pass this somewhere into the context in your template. Let’s assume you’ll want to do this on a page.

**page.php**

```php
<?php

$context = Timber::get_context();

$context['featured_products'] = new PostCollection(
    Timber::get_posts( wc_get_featured_product_ids() )
);

Timber::render( 'page.twig', $context );
```

**page.twig**

```twig
{{ include('woocommerce/products.twig', {
    posts: featured_products
}) }}
```

**woocommerce/products.twig**

```twig
{{ fn('woocommerce_product_loop_start') }}

{% for post in posts %}
    {{ fn('wc_get_template_part', 'content', 'product' ) }}
{% endfor %}

{{ fn('woocommerce_product_loop_end') }}
```

**Comment by azeem-khan** [comment]
Thank you so much, that has worked! One quick question. How would you be able to limit the amount of featured products are shown? For example, the client may select 7 in the dashboard but on the website, there should only be 4?

**Comment by gchtr** [comment]
> How would you be able to limit the amount of featured products are shown? For example, the client may select 7 in the dashboard but on the website, there should only be 4?

The easiest way to do this is probably to use `array_slice()` or something similar to limit the length of the array:

```
$ids = array_slice( wc_get_featured_product_ids(), 0, 4 );

$posts = new PostCollection( Timber::get_posts( $ids ) );
```
