### ISSUE TITLE
woocommerce.php extra context does not appear in Twig

### ISSUE THREAD

**Issue by richmilns** [mindkomm/timber-integration-woocommerce#33]
Hello! I've just started using your fantastic Timber Integration for WooCommerce project. It's really made coding for WooCommerce about the most pleasurable it can be!

I've noticed one issue though so far, and it's a bit of a strange one. 

In my theme, I have `woocommerce.php` which has some code inside to do extra stuff depending on what part of WooCommerce we are viewing, e.g.

**woocommerce.php**
```php
use Timber\Integrations\WooCommerce\WooCommerce;
use Timber\Timber;
$extra_context = [];
if (is_singular('product')) {
    // default related products from a specific category instead of random
    $extra_context['default_related_products'] = Timber::get_posts([
        'post_type' => 'product',
        'post_status' => 'publish',
        'posts_per_page' => 10,
        'suppress_filters' => true,
        'tax_query' => [
            [
                'taxonomy' => 'product_cat',
                'field'    => 'slug',
                'terms'    => 'default-related-products',
            ]
        ],
    ]);
}
WooCommerce::render_default_template($extra_context);
```

What I've found is that inside my `templates/woocommerce/single-product/related.twig` file, I am unable to see the variable `default_related_products` if I `{{ dump(_context) }}`. 

It's so strange because in other template files, I've taken a similar approach and it works just fine e.g. in `templates/woocommerce/archive-product.twig` I was setting a default header image for the page into `$extra_context` and I could access this fine in the Twig context. It seems to just affect the `templates/woocommerce/single-product.twig` and child `templates/woocommerce/single-product/*.twig` files.

My workaround has been to replace the final line above with the following code, but I wanted to highlight the issue in case there was anything else going on.

**woocommerce.php (amended final lines)**
```php
add_filter('timber/context', function ($context) use ($extra_context) {
    return array_merge($context, $extra_context);
}, 50);
WooCommerce::render_default_template();
```

Doing this, everything is working as expected again.

I started to debug the `Timber\Integrations\WooCommerce\WooCommerce` class and around line 376 if I debug the `$context` before and after it has been merged using `array_merge` I can see my `default_related_products` data.

Any ideas what might be going on here?

**Comment by gchtr** [comment]
That’s actually the expected behavior.

If you pass in context to `WooCommerce::render_default_template()`, the context will only be available for the outermost template file or any template that’s included with `{{ include() }}`.

If a view like **templates/woocommerce/single-product/related.twig** is rendered, then that template was initially called by WooCommerce’s `woocommerce_output_related_products()`, which then eventually calls `wc_get_template()`. This integration hooks into the `wc_get_template()` function, where we check for a Timber view with the name **templates/woocommerce/single-product/related.twig**.

The context for that template part is a new context. So when you pass in a context to `WooCommerce::render_default_template()`, it will never reach that template, because the entry point is different.

What you can do though is to add a separate context specifically for that template using the `timber/woocommerce/template/context` filter:

```php
add_filter( 'timber/woocommerce/template/context', function( $context, $template_name ) {
    if ( $template_name !== 'single-product/related.php' ) {
        return $context;
    }

    // This context will only be set if the single-product/related.php template is requested.

    $context['default_related_products'] = Timber::get_posts([
        'post_type' => 'product',
        'post_status' => 'publish',
        'posts_per_page' => 10,
        'no_found_rows' => true,
        'suppress_filters' => true,
        'tax_query' => [
            [
                'taxonomy' => 'product_cat',
                'field'    => 'slug',
                'terms'    => 'default-related-products',
            ]
        ],
    ]);

    return $context;
}, 10, 2 );
```

Hope that helps :).

**Comment by richmilns** [comment]
This is so helpful, thanks very much.
