### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by passiomatic** [mindkomm/timber-integration-woocommerce#4]
Hi there,

I'm trying the Timber -> WC integration but, after cloning and copying the plugin source code into the WP plugins folder when I activate it I get this error from the CMS:

```
Warning: require_once( ... /wp-content/plugins/timber-integration-woocommerce/vendor/autoload.php): failed to open stream: 
No such file or directory in ... /wp-content/plugins/timber-integration-woocommerce/timber-integration-woocommerce.php on line 10
```

It seems the plugin looks for a `vendor` folder, which isn't included in the source code. It _seems_ that the code should be placed in the Timber plugin instead, the directory structure is similar and there's a `vendor/autoload.php`.

Am I missing something? 

Note: I'm using latest WC 3.4.3 and Timber 1.7.1.

**Comment by gchtr** [comment]
Hey @passiomatic 

I’m sorry you’re running into this error. This is not your fault. The integration depends on Composer’s autoloading feature. I realized the documentation is wrong. In the current version, you can’t install it as a plugin, like you’re used to. You need Composer to install it. In on of the first versions of this integration, this wasn’t required. I [updated the documentation](https://github.com/MINDKomm/timber-integration-woocommerce/blob/master/docs/installation.md#installation) so it’s clear that Composer is needed for installation. I hope that it will be possible in a future version.

It wouldn’t work either if you place the folder into the Timber plugin, because Timber has different vendor dependencies.

You can install it if you run the Composer command **in your theme folder**:

```
composer require mindkomm/timber-integration-woocommerce
```

And you would then have to require the `vendor/autoload.php` file in your **functions.php** file, which loads in all the dependencies:

```php
require_once 'vendor/autoload.php';
```

But of course, for the command to work, you need Composer first. If you’re not familiar with Composer, I suggest you head on to [Composer’s documentation](https://getcomposer.org/doc/00-intro.md) to get started.

**Comment by passiomatic** [comment]
Thank you for the reply. Had no issues installing composer locally. Unfortunately it says my PHP version is outdated:

```
[InvalidArgumentException]                                                   
Package mindkomm/timber-integration-woocommerce at version  has a PHP requirement incompatible with your PHP version (5.5.38)    
```

It's the stock PHP version that comes with El Capitan and I'm no PHP wizard so, for now, I believe I'll continue to use ACF and Timber _without_ your plugin. It's less convenient but the idea to upgrade the PHP version on my dev machine where I have other website to keep updated almost daily is not very appealing. :) Thank you anyway!
