### ISSUE TITLE
Unexpected "do_action" tag

### ISSUE THREAD

**Issue by IngoVals** [mindkomm/timber-integration-woocommerce#8]
I get this error on the main WooCommerce site using the default _archive-product.twig_

FYI I cheated on the installation, my Docker setup didn't take into account Vendor folders so I had to manually set the php files from this plugin into the theme and required them all in _functions.php_

It should work right?

```
Fatal error:
    Uncaught Twig_Error_Syntax: Unexpected "do_action" tag (expecting closing tag for the "block" tag defined near line 4). in /var/www/html/wp-content/themes/rut/views/archive-product.twig:80
Stack trace: 
    #0 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/TokenParser/Block.php(40): Twig_Parser->subparse(Array, true) 
    #1 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Parser.php(192): Twig_TokenParser_Block->parse(Object(Twig_Token)) 
    #2 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Parser.php(105): Twig_Parser->subparse(NULL, false) 
    #3 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(716): Twig_Parser->parse(Object(Twig_TokenStream)) 
    #4 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(774): Twig_Environment->parse(Object(Twig_TokenStream)) 
    #5 /var/www/html/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Environment-> in /var/www/html/wp-content/themes/rut/views/archive-product.twig on line 80
```

**Comment by gchtr** [comment]
Hey @IngoVals, thanks for pointing this out!

There was indeed an error in **archive-product.twig**, which I fixed in https://github.com/mindkomm/timber-integration-woocommerce/commit/d21b5701a6b3bd91e95c9d70b404308b923132c6. This will make it into the next release. Maybe you’ll want to apply the same changes to your **archive-product.twig**?

> FYI I cheated on the installation, my Docker setup didn't take into account Vendor folders so I had to manually set the php files from this plugin into the theme and required them all in functions.php

This is actually the proper way to do it 👍, but I realized it’s not documented properly. I’ve used Composer in so many projects, I’m already really used to do it like this – and sometimes forget that it’s not always so obvious. I fixed this in https://github.com/mindkomm/timber-integration-woocommerce/commit/a90dd8ae08c74f56aec10e05d2ac10d73c40dbc8.

**Comment by IngoVals** [comment]
😆

I was so certain this was some PHP or Timber/Twig error that I didn't notice that this was just a simple typo.

Can't see the forest for all the trees.
